services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - internal-network
    ports:
      - "6379:6379"
  barbell-robot-mysql:
    image: mysql:8.4
    container_name: dev-bbr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RDBMS_PASSWORD}
    restart: always
    networks:
      - barbellrobot-backend
    volumes:
      - barbellrobot-mysql-data:/var/lib/mysql
  find-my-pet-mysql:
    image: mysql:8.4
    container_name: dev-fmp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RDBMS_PASSWORD}
    restart: always
    networks:
      - find-my-pet-backend
    volumes:
      - find-my-pet-mysql-data:/var/lib/mysql

networks:
  barbellrobot-backend:
    driver: bridge
    name: barbellrobot-backend
  find-my-pet-backend:
    driver: bridge
    name: find-my-pet-backend
  internal-network:
    driver: bridge
    name: internal-network

volumes:
  barbellrobot-mysql-data:
  find-my-pet-mysql-data: