services:
  reverse-proxy:
    image: traefik:v2.9
    container_name: dev-traefik
    # TODO: dashboard port change
    command:
      #      - "--api.insecure=true"
      - "--entrypoints.metrics.address=:8080"
      - "--providers.docker=true"
      #      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=wy9295@naver.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "8080:8080"
      - "443:443"
    #      - "80:80"
    #      - "8081:8081"
    networks:
      - internal-network
      - find-my-pet-backend
      - barbellrobot-backend
      - auth-server
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    #      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=traefik"
  # service
  auth-server:
    image: 'wy9295/auth-server:d17bb9acc17b2ae02a1b1bc326e6fa65c41763b8'
    container_name: dev-auth
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.auth-server-host.rule=Host(`woo-auth.duckdns.org`)"
#      - "traefik.http.routers.auth-server-host.priority=100"
#      - "traefik.http.routers.auth-server-host.entrypoints=websecure"
#      - "traefik.http.routers.auth-server-host.tls=true"
#      - "traefik.http.routers.auth-server-host.tls.certresolver=myresolver"
#      - "traefik.http.services.auth-server-host.loadbalancer.server.port=8080"

#      - "traefik.http.routers.auth-server-path.rule=PathPrefix(`/api/v1/auth`)"
#      - "traefik.http.routers.auth-server-path.priority=90"
#      - "traefik.http.routers.auth-server-path.entrypoints=websecure"
#      - "traefik.http.routers.auth-server-path.tls=true"
#      - "traefik.http.routers.auth-server-path.tls.certresolver=myresolver"
#      - "traefik.http.services.auth-server-path.loadbalancer.server.port=8080"
#      - "traefik.docker.network=internal-network"
    networks:
      - internal-network
      - auth-server
      - barbellrobot-backend
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RDBMS_URL=dev-bbr-mysql
      - RDBMS_USERNAME=${RDBMS_USERNAME}
      - RDBMS_PASSWORD=${RDBMS_PASSWORD}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - ACCESS_EXPIRE_MILLIS=${ACCESS_EXPIRE_MILLIS}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - REFRESH_EXPIRE_MILLIS=${REFRESH_EXPIRE_MILLIS}
  find-my-pet-backend:
    image: 'wy9295/find-my-pet-backend:df59b35269b10c48e7fcddb682b006471a21ccab'
    container_name: dev-fmp-backend
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.find-my-pet-backend.rule=Host(`find-my-pet.duckdns.org`)"
#      - "traefik.http.services.find-my-pet-backend.loadbalancer.server.port=8080"
#      - "traefik.http.routers.find-my-pet-backend.entrypoints=websecure"
#      - "traefik.http.routers.find-my-pet-backend.tls=true"
#      - "traefik.http.routers.find-my-pet-backend.tls.certresolver=myresolver"
#      - "traefik.docker.network=find-my-pet-backend"
    networks:
      - internal-network
      - find-my-pet-backend
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RDBMS_URI=dev-fmp-mysql
      - RDBMS_USERNAME=${RDBMS_USERNAME}
      - RDBMS_PASSWORD=${RDBMS_PASSWORD}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - ACCESS_EXPIRE_MILLIS=${ACCESS_EXPIRE_MILLIS}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - REFRESH_EXPIRE_MILLIS=${REFRESH_EXPIRE_MILLIS}
      - CLOUD_FRONT_DOMAIN_NAME=${CLOUD_FRONT_DOMAIN_NAME}
      - FMP_KAKAO_CLIENT_ID=${FMP_KAKAO_CLIENT_ID}
      - FMP_GOOGLE_CLIENT_ID=${FMP_GOOGLE_CLIENT_ID}
      - FMP_GOOGLE_CLIENT_SECRET=${FMP_GOOGLE_CLIENT_SECRET}
  barbellrobot-backend:
    image: 'wy9295/barbellrobot-backend:3ada73884b3b6fc4b0a011f0c5b3615c248fe14a'
    container_name: dev-bbr-backend
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.barbellrobot-backend.rule=Host(`wooyoung.duckdns.org`)"
#      - "traefik.http.services.barbellrobot-backend.loadbalancer.server.port=8080"
#      - "traefik.http.routers.barbellrobot-backend.entrypoints=websecure"
#      - "traefik.http.routers.barbellrobot-backend.tls=true"
#      - "traefik.http.routers.barbellrobot-backend.tls.certresolver=myresolver"
#      - "traefik.docker.network=barbellrobot-backend"
    networks:
      - internal-network
      - barbellrobot-backend
    volumes:
      - /root/google/key.json:/root/.config/gcloud/key.json:ro
    command: [ "sh", "-c", "gcloud auth activate-service-account --key-file=/root/.config/gcloud/key.json && java -jar app.jar" ]
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RDBMS_URI=dev-bbr-mysql
      - RDBMS_USERNAME=${RDBMS_USERNAME}
      - RDBMS_PASSWORD=${RDBMS_PASSWORD}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GEMINI_PROJECT_ID=${GEMINI_PROJECT_ID}
      - GEMINI_LOCATION=${GEMINI_LOCATION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - ACCESS_EXPIRE_MILLIS=${ACCESS_EXPIRE_MILLIS}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - REFRESH_EXPIRE_MILLIS=${REFRESH_EXPIRE_MILLIS}
      - CLOUD_FRONT_DOMAIN_NAME=${CLOUD_FRONT_DOMAIN_NAME}
  # Databases
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - internal-network
    ports:
      - "6379:6379"
  barbell-robot-mysql:
    image: mysql:8.4
    container_name: dev-bbr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RDBMS_PASSWORD}
    restart: always
    networks:
      - barbellrobot-backend
    volumes:
      - barbellrobot-mysql-data:/var/lib/mysql
  find-my-pet-mysql:
    image: mysql:8.4
    container_name: dev-fmp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RDBMS_PASSWORD}
    restart: always
    networks:
      - find-my-pet-backend
    volumes:
      - find-my-pet-mysql-data:/var/lib/mysql
  # Observability
  prometheus:
    image: prom/prometheus:latest
    container_name: dev-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - reverse-proxy
      - find-my-pet-backend
      - barbellrobot-backend
    labels:
      - "traefik.enable=false"
    networks:
      - internal-network
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - IP_ALLOW_LIST=${IP_ALLOW_LIST}
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal-network"
      - "traefik.http.routers.grafana.rule=Host(`wrafana.duckdns.org`)"
      - "traefik.http.middlewares.grafana-ipwhitelist.ipwhitelist.sourcerange=${IP_ALLOW_LIST}"
      - "traefik.http.routers.grafana.middlewares=grafana-ipwhitelist@docker"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    networks:
      - internal-network
  gateway:
    image: 'wy9295/gateway:427a1923732fb51424791ea39c9f02e522b69ae1'
    container_name: dev-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`woo-auth.duckdns.org`) || Host(`find-my-pet.duckdns.org`) || Host(`wooyoung.duckdns.org`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.docker.network=gateway"
    networks:
      - internal-network
      - gateway
    environment:
      - BBR_HOST=dev-bbr-backend
      - FMP_HOST=dev-fmp-backend
      - AUTH_HOST=dev-auth
  eureka:
    image: 'wy9295/eureka:4ca3b7545c6397cedaf1b14fc48971fda7c5d232'
    container_name: dev-eureka
    ports:
      - "8761:8761"
    networks:
      - internal-network

networks:
  barbellrobot-backend:
    driver: bridge
    name: barbellrobot-backend
  find-my-pet-backend:
    driver: bridge
    name: find-my-pet-backend
  internal-network:
    driver: bridge
    name: internal-network
  external-network:
    driver: bridge
    name: external-network
  auth-server:
    driver: bridge
    name: auth-server
  gateway:
    driver: bridge
    name: gateway

volumes:
  barbellrobot-mysql-data:
  find-my-pet-mysql-data:
  grafana_data:
