version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.9
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == my
    command:
      - "--entrypoints.metrics.address=:8080"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.eureka.address=:8761"
      - "--accesslog=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=wy9295@naver.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - internal-network
      - find-my-pet-backend
      - barbellrobot-backend
      - auth-server
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=traefik"

  kafka1:
    image: 'bitnami/kafka:latest'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == pve
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - CLUSTER_ID="YyV8UqkzTOG4JfG0xVHoWw"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka1:/bitnami/kafka/data
    networks:
      - internal-network

networks:
  barbellrobot-backend:
    driver: overlay
    attachable: true
    name: barbellrobot-backend
  find-my-pet-backend:
    driver: overlay
    attachable: true
    name: find-my-pet-backend
  internal-network:
    driver: overlay
    attachable: true
    name: internal-network
  external-network:
    driver: overlay
    attachable: true
    name: external-network
  auth-server:
    driver: overlay
    attachable: true
    name: auth-server
  gateway:
    driver: overlay
    attachable: true
    name: gateway

volumes:
  kafka1:
  letsencrypt:
    driver: local