services:
  reverse-proxy:
    image: traefik:v2.9
    container_name: dev-traefik
    # TODO: dashboard port change
    command:
      #      - "--api.insecure=true"
      - "--entrypoints.metrics.address=:8080"
      - "--providers.docker=true"
      #      - "--entrypoints.web.address=:80"
      - "--entrypoints.eureka.address=:8761"
      - "--accesslog=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=wy9295@naver.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "8080:8080"
      - "443:443"
    #      - "80:80"
    #      - "8081:8081"
    networks:
      - internal-network
      - find-my-pet-backend
      - barbellrobot-backend
      - auth-server
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    #      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "job=traefik"
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    environment:
      - KAFKA_CFG_NODE_ID=1 # 고유한 노드 ID 설정
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - CLUSTER_ID="YyV8UqkzTOG4JfG0xVHoWw" # Kafka Cluster ID
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka1:/bitnami/kafka/data
    networks:
      - internal-network

networks:
  barbellrobot-backend:
    driver: bridge
    name: barbellrobot-backend
  find-my-pet-backend:
    driver: bridge
    name: find-my-pet-backend
  internal-network:
    driver: bridge
    name: internal-network
  external-network:
    driver: bridge
    name: external-network
  auth-server:
    driver: bridge
    name: auth-server
  gateway:
    driver: bridge
    name: gateway

volumes:
  kafka1: