global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dev-traefik'
    static_configs:
      - targets: ['dev-traefik:8080']
  - job_name: 'dev_swarm-services'
    dockerswarm_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: "dev_(.*)"
        target_label: "job"
      - source_labels: [__meta_dockerswarm_task_name]
        target_label: "instance"
      - source_labels: [__meta_dockerswarm_network_name]
        target_label: "network"
    metrics_path: "/actuator/prometheus"
    scheme: "http"
#  - job_name: 'dev_bbr_backend'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'dev-bbr-backend:8080' ]
#  - job_name: 'dev-fmp-backend'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'dev-fmp-backend:8080' ]
#  - job_name: 'dev-auth-server'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'dev-auth:8080' ]
#  - job_name: 'dev-gateway'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'dev-gateway:8080' ]
  - job_name: 'infra'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']