global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dev_traefik'
    static_configs:
      - targets: ['dev_traefik']
  - job_name: 'dev_bbr_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev_bbr_backend' ]
  - job_name: 'dev_fmp_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev_fmp_backend' ]
