global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dev-traefik'
    static_configs:
      - targets: ['dev-traefik:8080']
  - job_name: 'dev_bbr_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-bbr-backend:8080' ]
  - job_name: 'dev-fmp-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-fmp-backend:8080' ]
  - job_name: 'dev-auth-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-auth:8080' ]
  - job_name: 'dev-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-gateway:8080' ]
  - job_name: 'infra'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']