api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: wy9295@naver.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO
  format: json

accessLog:
  format: json