global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dev-traefik'
    static_configs:
      - targets: ['dev-traefik:8080']

  - job_name: 'dev_swarm-services'
    dockerswarm_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
        role: tasks  # role을 명시적으로 추가
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: "dev_(.*)"
        target_label: "job"
      - source_labels: [__meta_dockerswarm_task_name]
        target_label: "instance"
      - source_labels: [__meta_dockerswarm_network_name]
        target_label: "network"
    metrics_path: "/actuator/prometheus"
    scheme: "http"

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: A
        port: 9100
