global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'application'
    dns_sd_configs:
      - names:
          - 'tasks.auth-server'
          - 'tasks.find-my-pet-backend'
          - 'tasks.gateway'
          - 'tasks.orchestrator'
          - 'tasks.eureka'
        type: A
        port: 8080
    metrics_path: '/actuator/prometheus'

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: A
        port: 9100
