global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_application'
    dns_sd_configs:
      - names:
          - 'tasks.auth-server'
          - 'tasks.find-my-pet-backend'
          - 'tasks.gateway'
          - 'tasks.orchestrator'
          - 'tasks.eureka'
          - 'tasks.storage'
          - 'tasks.forest'
          - 'tasks.mirror-view-backend'
        type: A
        port: 8080
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __meta_dns_sd_name ]
        regex: 'tasks\.(.+)'
        target_label: 'application'

  - job_name: 'node_exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: A
        port: 9100