name: Deploy Loki and Grafana via Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      services:
        description: "Select services to deploy (comma-separated if multiple)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - loki
          - grafana
          - prometheus
          - node_exporter
jobs:
  deploy-loki-grafana:
    runs-on: [self-hosted, label-deploy2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy Loki and Grafana with Docker Compose
        env:
          IP_ALLOW_LIST: ${{ secrets.IP_ALLOW_LIST }}
        shell: bash
        run: |
          echo "Initializing Docker Swarm (if not already initialized)..."
          docker swarm init || echo "Swarm already initialized"

          if [[ "${{ env.SERVICES }}" == "all" ]]; then
            echo "Deploying all services to Swarm..."
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/observability/docker-compose.yml" ${{ env.ENVIRONMENT }}
          else
            echo "Deploying selected service: ${{ env.SERVICES }}"
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/observability/docker-compose.yml" ${{ env.ENVIRONMENT }}
          fi

          echo "Checking deployed services..."
          docker service ls
