name: Deploy Loki and Grafana via Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-loki-grafana:
    runs-on: [self-hosted, label-deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy Loki and Grafana with Docker Compose
        env:
          IP_ALLOW_LIST: ${{ secret.IP_ALLOW_LIST }}
        shell: bash
        run: docker-compose -f "compose/${{ env.ENVIRONMENT }}/docker-compose.yml" up -d loki grafana
