name: Deploy MySQL and Redis via Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      services:
        description: "Select services to deploy (comma-separated if multiple)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - redis
          - find-my-pet-mysql
          - barbell-robot-mysql
          - mongodb
jobs:
  deploy-databases:
    runs-on: [self-hosted, label-deploy2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy MySQL and Redis with Docker Swarm
        shell: bash
        env:
          RDBMS_USERNAME: ${{ secrets.RDBMS_USERNAME }}
          RDBMS_PASSWORD: ${{ secrets.RDBMS_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
        run: |
          echo "Initializing Docker Swarm (if not already initialized)..."
          docker swarm init || echo "Swarm already initialized"

          if [[ "${{ env.SERVICES }}" == "all" ]]; then
            echo "Deploying all services to Swarm..."
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/database/docker-compose.yml" ${{ env.ENVIRONMENT }}
          else
            echo "Deploying selected service: ${{ env.SERVICES }}"
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/database/docker-compose.yml" ${{ env.ENVIRONMENT }}
          fi

          echo "Checking deployed services..."
          docker service ls
