name: Deploy MySQL and Redis via Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      services:
        description: "Select services to deploy (comma-separated if multiple)"
        required: true
        default: "all"
        type: choice
        options:
          - redis
          - find-my-pet-mysql
          - barbell-robot-mysql
jobs:
  deploy-databases:
    runs-on: [self-hosted, label-deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy MySQL and Redis with Docker Compose
        shell: bash
        env:
          RDBMS_USERNAME: ${{ secrets.RDBMS_USERNAME }}
          RDBMS_PASSWORD: ${{ secrets.RDBMS_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          if [[ "${{ env.SERVICES }}" == "all" ]]; then
            echo "Deploying all services..."
            docker-compose -f "compose/${{ env.ENVIRONMENT }}/database/docker-compose.yml" up -d
          else
            echo "Deploying selected service: ${{ env.SERVICES }}"
            docker-compose -f "compose/${{ env.ENVIRONMENT }}/database/docker-compose.yml" up -d "${{ env.SERVICES }}"
          fi
