name: Deploy Middleware via Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      services:
        description: "Select services to deploy (comma-separated if multiple)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - reverse-proxy
          - kafka1

jobs:
  deploy-middleware:
    runs-on: [self-hosted, label-deploy2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "SERVICES=${{ inputs.services }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create nginx config
        run: |
          docker config rm nginx_config || true
          docker config create ${{ env.ENVIRONMENT }}_nginx_config compose/${{ env.ENVIRONMENT }}/default.template

      - name: Deploy with Docker Compose
        shell: bash
        run: |
          echo "Initializing Docker Swarm (if not already initialized)..."
          docker swarm init || echo "Swarm already initialized"

          if [[ "${{ env.SERVICES }}" == "all" ]]; then
            echo "Deploying all services to Swarm..."
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/docker-compose.yml" ${{ env.ENVIRONMENT }}
          else
            echo "Deploying selected service: ${{ env.SERVICES }}"
            docker stack deploy -c "compose/${{ env.ENVIRONMENT }}/docker-compose.yml" ${{ env.ENVIRONMENT }}
          fi

          echo "Checking deployed services..."
          docker service ls

