#name: Deploy via Docker Compose
#
#on:
#  repository_dispatch:
#    types: [ update_app_image_tag ]
#  workflow_dispatch:
#
#jobs:
#  deploy:
#    runs-on: [self-hosted, label-deploy]
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      # linux 로 변경하면 삭제
#      - name: Set PowerShell execution policy
#        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force
#        shell: powershell
#
#
#      - name: Set environment variables
#        run: |
#          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
#          echo "APP_NAME=barbellrobot-backend" >> $GITHUB_ENV
#          echo "ENVIRONMENT=${{ github.event.client_payload.environment }}" >> $GITHUB_ENV
#
#      - name: Determine compose file path
#        run: |
#          if [ "${{ env.ENVIRONMENT }}" == "dev" ]; then
#            echo "COMPOSE_FILE=compose/dev/docker-compose.yml" >> $GITHUB_ENV
#          elif [ "${{ env.ENVIRONMENT }}" == "prod" ]; then
#            echo "COMPOSE_FILE=compose/prod/docker-compose.yml" >> $GITHUB_ENV
#          else
#            echo "Invalid environment: ${{ env.ENVIRONMENT }}"
#            exit 1
#          fi
#
#      - name: Replace image tag in docker-compose.yml
#        run: |
#          sed -i '/^[[:space:]]*image:[[:space:]]*'"${{ env.APP_NAME }}"'\s*$/ {n;s/\(.*\):.*/\1:'"${{ env.IMAGE_TAG }}"'/}' "${{ env.COMPOSE_FILE }}"
#
#      - name: Deploy with Docker Compose
#        run: docker-compose -f "${{ env.COMPOSE_FILE }}" up -d "${{ env.APP_NAME }}"

name: Deploy via Docker Compose

on:
  repository_dispatch:
    types: [ update_app_image_tag ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, label-deploy]
    defaults:
      run:
        shell: powershell -NoProfile -ExecutionPolicy Bypass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          $env:IMAGE_TAG = '${{ github.event.client_payload.image_tag }}'
          $env:APP_NAME = 'barbellrobot-backend'
          $env:ENVIRONMENT = '${{ github.event.client_payload.environment }}'
          Add-Content -Path $env:GITHUB_ENV -Value "IMAGE_TAG=$($env:IMAGE_TAG)"
          Add-Content -Path $env:GITHUB_ENV -Value "APP_NAME=$($env:APP_NAME)"
          Add-Content -Path $env:GITHUB_ENV -Value "ENVIRONMENT=$($env:ENVIRONMENT)"

      - name: Determine compose file path
        run: |
          if ($env:ENVIRONMENT -eq 'dev') {
            $env:COMPOSE_FILE = 'compose/dev/docker-compose.yml'
          } elseif ($env:ENVIRONMENT -eq 'prod') {
            $env:COMPOSE_FILE = 'compose/prod/docker-compose.yml'
          } else {
            Write-Error "Invalid environment: $($env:ENVIRONMENT)"
            exit 1
          }
          Add-Content -Path $env:GITHUB_ENV -Value "COMPOSE_FILE=$($env:COMPOSE_FILE)"

      - name: Replace image tag in docker-compose.yml
        run: |
          $composeFile = $env:COMPOSE_FILE
          $appName = $env:APP_NAME
          $imageTag = $env:IMAGE_TAG

          $content = Get-Content $composeFile

          $newContent = $content | ForEach-Object {
            if ($_ -match "^\s*image:\s*$appName(:.*)?$") {
              "image: $appName:$imageTag"
            } else {
              $_
            }
          }

          Set-Content -Path $composeFile -Value $newContent

      - name: Deploy with Docker Compose
        run: docker-compose -f "$env:COMPOSE_FILE" up -d "$env:APP_NAME"
