name: Update prometheus configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
jobs:
  deploy-loki-grafana:
    runs-on: [self-hosted, label-deploy2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: bash
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy Loki and Grafana with Docker Compose
        env:
          IP_ALLOW_LIST: ${{ secrets.IP_ALLOW_LIST }}
        shell: bash
        run: |
          SERVICE_NAME=${ENVIRONMENT}_prometheus
          
          echo "Forcing restart of '${SERVICE_NAME}' to pick up new prometheus.yml bind-mount..."
          docker service update --force $SERVICE_NAME
          
          echo "Calling Prometheus hot-reload API..."
          curl -X POST http://localhost:9090/-/reload

